services:
  scraper:
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
    volumes:
      - .:/usr/src/app
    cap_add:
      - SYS_ADMIN
    init: true

volumes:
  scraper.vol:
    driver: local
